# Generated by Django 4.2.1 on 2023-05-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('красный', 'Красный'), ('синий', 'Синий'), ('желтый', 'Желтый')], max_length=10, verbose_name='Оттенок цветка')),
            ],
            options={
                'verbose_name': 'Цветок',
                'verbose_name_plural': 'Цветы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название лота')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кол-во товара')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за шт.')),
                ('hide_from_customers', models.BooleanField(default=False, verbose_name='Не показывать товар покупателям')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.flower')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
            },
        ),
    ]
